# Generated by Django 2.1.9 on 2019-07-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytbl',
            name='highcategoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.HighCategoryTBL', verbose_name='上位カテゴリID'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.CategoryTBL', verbose_name='カテゴリID'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='entrydate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録年月日時分秒'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='goodsdescription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='商品記述'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='goodsurl',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='商品画像URL'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='salesenddate',
            field=models.DateField(blank=True, null=True, verbose_name='販売終了年月日'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新年月日時分秒'),
        ),
    ]
