# Generated by Django 2.1.9 on 2019-07-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20190716_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytbl',
            options={'verbose_name_plural': 'カテゴリマスタ'},
        ),
        migrations.AlterModelOptions(
            name='goodstbl',
            options={'verbose_name_plural': '商品マスタ'},
        ),
        migrations.AlterModelOptions(
            name='highcategorytbl',
            options={'verbose_name_plural': '上位カテゴリマスタ'},
        ),
        migrations.AlterUniqueTogether(
            name='goodstbl',
            unique_together={('productno', 'sizename', 'colorname')},
        ),
    ]
